# Generated by Django 2.1.5 on 2019-02-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.FileField(upload_to='')),
                ('Nama', models.TextField(max_length=225)),
                ('quote', models.TextField(max_length=225)),
            ],
        ),
    ]
