# Generated by Django 2.1.5 on 2019-02-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='pengalaman',
            field=models.TextField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
