# Generated by Django 2.1.5 on 2019-02-13 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('teks', models.TextField(max_length=1000)),
                ('tanggal_dibuat', models.DateField(default=datetime.date(2019, 2, 13))),
            ],
        ),
        migrations.DeleteModel(
            name='Postingan',
        ),
    ]
