# Generated by Django 2.1.5 on 2019-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190213_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gambar',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
