# Generated by Django 2.1.5 on 2019-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
